config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos do
    member do
      put :like_video
      put :seen_video
      put :seen_count
      post :share_video_with_user
    end
     resources :comments
  end
  resources :analytics
  

   root 'homes#index'

end

app/models/analytic.rb
class Analytic < ActiveRecord::Base
	belongs_to :user
	belongs_to :video
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :video
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :videos
  has_many :analytics
  has_many :comments
  has_many :user_videos
	has_many :videos ,:through => :user_videos
end

app/models/user_video.rb
class UserVideo < ActiveRecord::Base
	belongs_to :user
	belongs_to :video
end

app/models/video.rb
class Video < ActiveRecord::Base

	 mount_uploader :video, VideoUploader
	 mount_uploader :image , ImageUploader
	 belongs_to :user
	 has_many :analytics
	 has_many :comments
	 has_many :user_videos
	 has_many :users ,:through => :user_videos
	 validates_presence_of :title , :description 

	 include VideoScreenshot
	 after_create :save_video_screenshot

	def self.like_status(video_id , user)
	 		@analytics = fetch_analytic(video_id ,user)
  	if @analytics.present?
  		@analytics.update_attributes(like: !@analytics.like)
  	else
  		@analytics = create_analytic(user , video_id)
  	end
    v = Video.find(video_id)
  	v.like_count_update
	end
  
  def like_count_update
  	self.update_attributes(like_count: self.fetch_like_count )
  end

	def self.seen_status(video_id , user)
		
		@analytics = fetch_analytic(video_id ,user)
		if @analytics.present?
		  
			 @analytics.update_attributes(seen: true) unless @analytics.seen
		
		else
			@analytics = create_analytic( user , video_id , false,true)
		end
	end

	def self.fetch_videos(current_user , video_type = 'Public')
	  Video.where('video_type = ? AND user_id <> ?', video_type, current_user.id ) + current_user.videos
	end

  def self.fetch_seen_count(video_id , seen = true)
    Analytic.where(video_id: video_id , seen: seen).count
  end

	def self.fetch_analytic(video_id ,user)
		Analytic.where(video_id: video_id,user_id: user.id).last
	end
  
  def self.create_analytic(user , video_id , like = true , seen = false)
  	Analytic.create(user_id: user.id,video_id: video_id ,seen: seen , like: like)
  end

  def fetch_like_count
  	self.analytics.where(like: true).count
  end

	def save_video_screenshot
	 convert_to_jpg()
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	
	def index
		@comments = Comment.all
	end


	def create
		@video = Video.find(params[:video_id])
   @comment = @video.comments.new(comment_params)#create a new comment for current video
	 
	   if @comment.save 
	   	
	    redirect_to video_path(@video)
	   else
	   	@comments = @video.comments
	   	render template: '/videos/show'
	   end
	end

	def destroy
		@video = Video.find(params[:video_id])
    @comment = Comment.find(params[:id])
   	@comment.destroy
   	redirect_to article_path(@video)
	end 



	private
	def comment_params
    params.require(:comment).permit(:comment,:video_id , :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
   before_filter :authenticate_user!
	def index
		
   
    @fetch_videos = Video.fetch_videos(current_user,'Public')
   
    #@index_videos = (@videos + @fetch_videos)
		@users = User.all
	end

	def new
		@video = Video.new
		@users = User.all
	end

	def create
   
    params[:video] = params[:video].merge(user_id: current_user.id)

		@video = Video.new(video_params)
    current_user.videos << @video
    
		if @video.save
       redirect_to videos_path ,:notice => "Saved successfully"

		else
      flash.now.alert = " #{@video.errors.full_messages.join(",")}" if @video.errors.any?
			render('new') 
		end
	end
	
  def show

  	@video = Video.find(params[:id])
  	@analytics = Analytic.where(video_id: @video.id,user_id: current_user.id).last
    @count = Video.fetch_seen_count(@video.id , true)
    @videos = current_user.videos
    @fetch_videos = Video.fetch_videos(current_user,'public')
    @comments = @video.comments
    @comment = @video.comments.new
  end

  
  def destroy
  	@video = Video.find(params[:id])
  	if @video.destroy
  		redirect_to videos_path ,:notice => "Destroy successfully"
  	end
  end

  def like_video
  	@video = Video.find(params[:id])
  	Video.like_status(@video.id , current_user)
   	redirect_to video_path    
  end

  def seen_video
  	@video = Video.find(params[:id])
  	Video.seen_status(@video.id , current_user)

    respond_to do |format|
          format.html {
             redirect_to video_path 
           }

           format.js{
            render json: { success: true}
           }
    end 
  end

  def share_video_with_user
    #binding.pry
    @video = Video.find(params[:id])
    @users = User.find(params[:user])
    @users.each do |user|
      @video.users << user
    end
     redirect_to video_path(@video)
  end


  private
	def video_params
    params.require(:video).permit(:title, :description, :video ,:user_id ,:video_type,:like_count ,:videos_screenshot)
  end

  def analytics_params
  	params.require(:analytics).permit(:user_id ,:video_id,:like,:seen)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def class_for_flash_message(flash_type)
		case flash_type
		when "notice"
			"alert-success"
		when "alert"
			"alert-danger"
		when "error"
			"alert-danger"
		end	 	   
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
	 def edit_like_button
    if @analytics.try(:like) == true
    	 return 'unlike'
    else
    	  return 'like'
    end
	 end
end

app/views/comments/_form.html.erb
<div class ="container">
  <%= form_for [@video,@comment],:url => video_comments_path(@video), html: { class: "form-horizontal" } , :method => 'post' do |f| %>
          <div class= "text-center">
            <h4> Comment </h4>
          </div>
         <div class="form-group", "text-right">
            <label for="inputcomment" class="col-sm-2 control-label">Comment</label>
            <div class="col-sm-6">
              <%=  f.text_field :comment , class: "form-control" ,id: "inputcomment"%>
            </div>
          </div>
        <div class = "form-group","text-right">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "post comment" , class: "btn-btn-default" %>
          </div>
        </div>
  <%end %>
</div>

app/views/comments/index.html.erb
<div class ="container">
	<h4>Comment</h4>
	<% @comments.each do |comment| %>
	  <div class="panel panel-default">
	   <div class = "panel - heading">
	   </div>
	    <div class="panel-body">
	      <%= comment.comment %>
	    </div>  
	  </div>  
	<% end %>
</div>

app/views/homes/index.html.erb
<h1>Welcome!!!!!!</h1>
  <%if user_signed_in?%>

    <%content_for :breadcrumb do %>
    		 <ul class="breadcrumb">
    		 <li><%=link_to "Home" , root_path%></li>
    		 </ul>
    <%end%>

    <div class="btn-group btn-group-sm" >
      <button type="button" class="btn btn-default "><%= link_to "My Video",videos_path()  %>
      </button>
    </div>
      
    <div class="btn-group btn-group-sm" >
      <button type="button" class="btn btn-default "><%= link_to "Upload Video",new_video_path()  %>
      </button>
    </div>

  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Youtube</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%flash.each do |type,value|%>
		<div class="alert <%= class_for_flash_message(type.to_s)%>" role="alert"> 
			<%=value%>
		</div>
	<%end%> 
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div> 
			<!-- Collect the nav links, forms, and other content for toggling -->
			<ul class="nav navbar-nav"> 
				<li></li>
			</ul>
			<%if user_signed_in? %>
				<ul class ="nav navbar-nav">
					<li class = "active"><%= link_to "log out" ,destroy_user_session_path,:method => "delete"  %> 
					</li>

				</ul>
				<ul class ="nav navbar-nav">
					<li class = "active"> </li>
				</ul>
				<ul class ="nav navbar-nav">
					<li class = "active">

					</li>
				</ul>
				<div class = "text-right "style = "padding-top: 16px;display: inline;float: right;">

					Current User is :<%= current_user.name %> 
				</div>
			<%else%>
				<ul class="nav navbar-nav">
				<li class = "active " >
					<%= link_to " Sign In", new_user_session_path %></li>
				</ul>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active"><%= link_to "Sign up", new_user_registration_path %></li>
				</ul>
			<%end%>
		</div>
	</nav>
	<%= yield :breadcrumb %>
	<%= yield %>

</body>
</html>

app/views/videos/_comments.html.erb
	<div class = "container">
   	<% @comments.each_with_index do |comment, index| %>
 
   	<div class= "panel panel-default"> 
   
     <div class="panel-body">
      <%= comment.comment %>
      <%= link_to "Delete", video_comment_path(@video.id , comment.id), :method => "delete" unless comment.new_record?%> 
     </div> 
    <div class = "panel footer">
    </div>
    </div/>
 
    <% end %>
</div> 
</br> 

app/views/videos/_form.html.erb
<div class ="container">
  
  <%= form_for @video, :html => { class: "form-horizontal", :multipart => true} do |f| %>

  <div class="form-group ">
    <label for="inputtitle "class="col-sm-2 control-label" >Title</label>
    <div class="col-sm-6">
      <%=  f.text_field :title , class: "form-control" ,id: "inputtitle"%>
      
    </div>
  </div>

  <div class="form-group ">
    <label for="inputdescription "class="col-sm-2 control-label" >Description</label>
      <div class="col-sm-6">
      <%=  f.text_field :description , class: "form-control" ,id: "inputdescription"%>
      </div>
  </div>

  <div class="form-group ">
    <label for="InputFile "class="col-sm-2 control-label" >File input</label>
     <div class="col-sm-6">
      <%= f.file_field :video ,class: "form-control" ,id: "InputFile" %>
     </div>
  </div>
  <div class = "form_group ">
   <label for="Inputvideo " class="col-sm-2 control-label" >Select The Video Type</label>&nbsp;&nbsp;
   <div class="col-sm-6">
     <%= f.radio_button :video_type, 'Public', :checked => true %> 
     <label for="Inputradio" >Public</label>
     <%= f.radio_button :video_type, 'Private'%> 
     <label for="Inputradio" >Private</label>
   </div>
  </div>
  <div class="form-group ">
    <div class="col-sm-offset-2 col-sm-10">
     
      <%= f.submit %>
     </div>
  </div>   
<%end%>
</div>

app/views/videos/index.html.erb
<div class ="container">

    <div class="btn-group btn-group-sm" >
        <button type="button" class="btn btn-default"><%= link_to "Upload Video",new_video_path()  %>
        </button>
    </div>
    <%content_for :breadcrumb do %>
    <ul class="breadcrumb">
      <li><%= link_to "Home" ,root_path%></li>
      <li><%= link_to "Video List" %></li>
    </ul>
  <%end%>

    <h4>Video</h4>
   
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Video</th>
                <th>Video Type</th>
                <th>Likes</th>
                <th>Delete</th>
            </tr>
        </thead>
        
        <% @fetch_videos.each  do |video| %>

            <tbody>
                <tr>
                    <td>
                        <%= video.title%>
                    </td>
                    <td> <%= video.description%></td>
                    <td>
                        
                        <%= link_to  video.video , video_path(video)%>
                    </td>
                    <td> <%= video.video_type%></td>
                    <td><%=  video.fetch_like_count%></td>
                    <td>
                        <%= link_to "<span class='glyphicon glyphicon-remove btn btn-danger btn-xs'></span>".html_safe , video_path(video),:method => "delete"%> 

                    </td>                
                </tr>
            </tbody>
        <% end %>
    </table>
  <div class="btn-group btn-group-sm" >
        <button type="button" class="btn btn-default"><%= link_to "Back" ,root_path %>
        </button>
    </div>
</div>
    

app/views/videos/new.html.erb
<%= render :partial=>"form"%>

<div class="btn-group btn-group-sm" >
  <button type="button" class="btn btn-default"><%= link_to "Back" ,root_path %>
  </button>
</div>

app/views/videos/show.html.erb
<div class ="container">
  <%content_for :breadcrumb do %>
    <ul class="breadcrumb">
      <li><%= link_to "Home" , root_path%></li>
      <li><%= link_to "Videos",videos_path(@fetch_video) %></li>
      <li><%= link_to "#{@video.title}" %></li>
    </ul>
  <%end%>
  <div class = "Row">
    <div class="col-md-8">
      <%= @video.title%>
        <script src="http://jwpsrv.com/library/JTsFTGl3EeSnPgoORWfmyA.js"></script>
      <div id='myElement'>Loading the player ...</div>
      <script type='text/javascript'>
        jwplayer('myElement').setup({ 
          file: '<%= "#{@video.video_url}"%>', 
          height: 360, 
        
          width: 640 ,
          events: {
                onPlay: function (state) {
                //alert ("video start");
                  $.ajax({
                      type : "put" ,
                      url :"/videos/<%=@video.id%>/seen_video",
                      dataType : "json"

                    }).done(function( response ) {});
              }    
                   
              }
        
        });
      </script>
      </br>
      <div class="btn-group btn-group-sm col-sm-8" >
        <button type="button" class="btn btn-default col-sm-2"><%= link_to edit_like_button,like_video_video_path(@video) ,:method => :put %>
        </button>&nbsp;&nbsp;
      </div>
      <p><%=@count%> views</p>

      <a href="https://www.facebook.com/sharer/sharer.php?u=<%=@video.video_url%>" target="_blank">
        Share on Facebook
      </a>
      <a class="twitter-share-button"
        href="https://twitter.com/share">
        Tweet
      </a>
      <script type="text/javascript">
      window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
      </script>
       <%= form_tag share_video_with_user_video_path(@video), :method => 'post' do %>
     
      <%= select_tag :user,
      options_from_collection_for_select(User.all.where("id <> ?" ,current_user.id), "id", "email"),
       include_blank: true ,
       multiple: true,
       class: 'chosen-select' 
      %>
      <%= submit_tag "Share with user",:class => "btn btn-default  submit"%>
    <%end%>
      <%= render  partial: 'comments/form' , as: :comment%>
      <%= render  partial: 'videos/comments' %>
    </div>
   <%#binding.pry%>
    <div class="col-md-3">
    
      <div id = "nav" >
       
         <div id = "nav" >
        <%@fetch_videos.each do |fetch_video|%>
         <ul>
          <%#= image_tag "#{fetch_video.image}" , size:"100x100" , :class => "style_image"%>
         <%= link_to  "<span class='glyphicon glyphicon-play-circle' aria-hidden='true'>#{fetch_video.title}</span>#{image_tag "#{fetch_video.image}", size:'100x100' , :class => "style_image"}".html_safe  , video_path(fetch_video)%>
       </ul>
        <%end%>
      </div>
    </div>
    
    
  </div>
</div>